// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZCMfxTcRiEFRP1x16-fg-10FibyvxPU',
    appId: '1:373965490656:web:09b9644fd9a802b63f0385',
    messagingSenderId: '373965490656',
    projectId: 'workflow-66848',
    authDomain: 'workflow-66848.firebaseapp.com',
    storageBucket: 'workflow-66848.appspot.com',
    measurementId: 'G-PFXS4ZYPV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj_QjsaP5VgCb_ZP1cd6fUlwE-laWE8Us',
    appId: '1:373965490656:android:1aac60d655ec0eca3f0385',
    messagingSenderId: '373965490656',
    projectId: 'workflow-66848',
    storageBucket: 'workflow-66848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG8C4BDuCJkncoV4vxAXW6PX3MyvF55vI',
    appId: '1:373965490656:ios:f3156c968fdf93333f0385',
    messagingSenderId: '373965490656',
    projectId: 'workflow-66848',
    storageBucket: 'workflow-66848.appspot.com',
    iosClientId: '373965490656-5v7ievlcf7bi8mce2dan6lia9isigsur.apps.googleusercontent.com',
    iosBundleId: 'com.example.workflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG8C4BDuCJkncoV4vxAXW6PX3MyvF55vI',
    appId: '1:373965490656:ios:f3156c968fdf93333f0385',
    messagingSenderId: '373965490656',
    projectId: 'workflow-66848',
    storageBucket: 'workflow-66848.appspot.com',
    iosClientId: '373965490656-5v7ievlcf7bi8mce2dan6lia9isigsur.apps.googleusercontent.com',
    iosBundleId: 'com.example.workflow',
  );
}
